# Generated by Django 5.1.3 on 2026-03-22 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expediteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('pays', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('pays_destination', models.CharField(max_length=100)),
                ('ville_destination', models.CharField(max_length=100)),
                ('poids_colis', models.FloatField()),
                ('prix_total', models.FloatField()),
                ('commission', models.FloatField(default=0)),
                ('mode_paiement', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('orange', 'Orange Money'), ('mobile', 'Mobile Money')], max_length=20)),
                ('paiement_effectue', models.BooleanField(default=False)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voyageur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('pays_depart', models.CharField(max_length=100)),
                ('ville_depart', models.CharField(max_length=100)),
                ('pays_destination', models.CharField(max_length=100)),
                ('ville_destination', models.CharField(max_length=100)),
                ('date_depart', models.DateField()),
                ('heure_depart', models.TimeField()),
                ('date_arrivee', models.DateField()),
                ('heure_arrivee', models.TimeField()),
                ('poids_disponible', models.FloatField()),
                ('note', models.FloatField(default=5.0)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('complet', 'Complet'), ('termine', 'Terminé')], default='actif', max_length=20)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('mode_paiement', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('orange', 'Orange Money'), ('mobile', 'Mobile Money')], max_length=20)),
                ('statut', models.CharField(default='en_attente', max_length=20)),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voyageurs.expediteur')),
                ('voyageur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voyageurs.voyageur')),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('termine', 'Terminé')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voyageurs.expediteur')),
                ('voyageur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voyageurs.voyageur')),
            ],
        ),
    ]
