# Generated by Django 5.1.3 on 2026-03-22 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyageurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('commentaire', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('voyageur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voyageurs.voyageur')),
            ],
        ),
    ]
