# Generated by Django 5.1.3 on 2026-03-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyageurs', '0002_avis'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='date_reponse',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
