# Generated by Django 5.1.3 on 2026-03-26 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyageurs', '0003_demande_date_reponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voyageurs.expediteur')),
                ('voyageur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voyageurs.voyageur')),
            ],
        ),
    ]
