# Generated by Django 5.1.3 on 2026-03-31 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyageurs', '0004_matching'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediteur',
            name='date_paiement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expediteur',
            name='guest_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expediteur',
            name='reference_paiement',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='voyageur',
            name='guest_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expediteur',
            name='mode_paiement',
            field=models.CharField(choices=[('carte', 'Carte bancaire'), ('paypal', 'PayPal'), ('orange', 'Orange Money'), ('wave', 'Wave')], max_length=20),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=20)),
                ('contenu', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voyageurs.expediteur')),
                ('voyageur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voyageurs.voyageur')),
            ],
        ),
    ]
