# Generated by Django 5.1.3 on 2026-04-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyageurs', '0005_expediteur_date_paiement_expediteur_guest_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_profil', models.CharField(choices=[('voyageur', 'Voyageur'), ('expediteur', 'Expediteur')], max_length=20)),
                ('nom_complet', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('guest_id', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
