# Generated by Django 5.1.3 on 2026-04-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyageurs', '0006_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediteur',
            name='is_matched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voyageur',
            name='is_matched',
            field=models.BooleanField(default=False),
        ),
    ]
