# Generated by Django 5.1.3 on 2026-04-07 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyageurs', '0007_expediteur_is_matched_voyageur_is_matched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matching',
            name='expediteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchings', to='voyageurs.expediteur'),
        ),
        migrations.AlterField(
            model_name='matching',
            name='voyageur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchings', to='voyageurs.voyageur'),
        ),
        migrations.AlterUniqueTogether(
            name='matching',
            unique_together={('expediteur', 'voyageur')},
        ),
    ]
