# Generated by Django 5.1.3 on 2026-04-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyageurs', '0008_alter_matching_expediteur_alter_matching_voyageur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matching',
            name='statut',
            field=models.CharField(default='confirme', max_length=20),
        ),
        migrations.DeleteModel(
            name='Avis',
        ),
    ]
