# Generated by Django 5.1.3 on 2026-04-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyageurs', '0009_alter_matching_statut_delete_avis'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyageur',
            name='type_kg',
            field=models.CharField(choices=[('entier', 'Kg en entier (tout ou rien)'), ('detail', 'Kg en détail (fractionnable)')], default='entier', max_length=10),
        ),
        migrations.AlterField(
            model_name='voyageur',
            name='poids_disponible',
            field=models.FloatField(default=0),
        ),
    ]
