# Generated by Django 5.1.3 on 2026-04-12 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyageurs', '0010_voyageur_type_kg_alter_voyageur_poids_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='mode_paiement',
            field=models.CharField(choices=[('carte', 'Carte bancaire'), ('paypal', 'PayPal'), ('orange', 'Orange Money'), ('wave', 'Wave')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('bloque', '🔒 Bloqué (en escrow)'), ('debloque', '✅ Débloqué vers voyageur'), ('rembourse', '↩️ Remboursé'), ('echec', '❌ Échec')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='voyageur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voyageurs.voyageur'),
        ),
    ]
