# Generated by Django 5.1.3 on 2026-04-17 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyageurs', '0011_alter_transaction_mode_paiement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_id', models.CharField(max_length=100)),
                ('nom_complet', models.CharField(default='Utilisateur', max_length=200)),
                ('type_profil', models.CharField(default='inconnu', max_length=20)),
                ('sender', models.CharField(choices=[('user', 'Utilisateur'), ('admin', 'Admin')], max_length=20)),
                ('contenu', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='montant_commission',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='montant_voyageur',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='note_remboursement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('bloque', '🔒 Bloqué'), ('debloque', '✅ Débloqué vers voyageur'), ('rembourse', '↩️ Remboursé'), ('echec', '❌ Échec')], default='en_attente', max_length=20),
        ),
    ]
