# Generated by Django 5.1.3 on 2026-04-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyageurs', '0012_messagesupport_transaction_montant_commission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portefeuille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_id', models.CharField(max_length=100, unique=True)),
                ('nom_complet', models.CharField(default='', max_length=200)),
                ('solde', models.FloatField(default=0)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Retrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_id', models.CharField(max_length=100)),
                ('nom_complet', models.CharField(default='', max_length=200)),
                ('montant', models.FloatField()),
                ('mode_retrait', models.CharField(choices=[('orange', 'Orange Money'), ('paypal', 'PayPal'), ('carte', 'Carte bancaire'), ('wave', 'Wave')], max_length=20)),
                ('coordonnees', models.CharField(max_length=200)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('traite', '✅ Traité'), ('refuse', '❌ Refusé')], default='en_attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='expediteur',
            name='date_confirmation_expediteur',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expediteur',
            name='livraison_confirmee_expediteur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matching',
            name='date_livraison',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matching',
            name='livraison_confirmee_voyageur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matching',
            name='photo_livraison',
            field=models.ImageField(blank=True, null=True, upload_to='livraisons/'),
        ),
        migrations.AddField(
            model_name='message',
            name='est_photo_livraison',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='messages_photos/'),
        ),
        migrations.AlterField(
            model_name='matching',
            name='statut',
            field=models.CharField(default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='contenu',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('bloque', '🔒 Bloqué'), ('debloque', '✅ Débloqué vers voyageur'), ('rembourse', '↩️ Remboursé'), ('remboursement_demande', '🔴 Remboursement demandé'), ('echec', '❌ Échec')], default='en_attente', max_length=30),
        ),
    ]
