# Generated by Django 5.1.3 on 2026-04-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyageurs', '0013_portefeuille_retrait_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='debloque_par',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
