# Generated by Django 5.1.3 on 2026-05-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyageurs', '0014_transaction_debloque_par'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediteur',
            name='is_created_via_matching',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voyageur',
            name='is_created_via_matching',
            field=models.BooleanField(default=False),
        ),
    ]
