# Generated by Django 5.1.3 on 2026-05-08 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyageurs', '0015_expediteur_is_created_via_matching_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediteur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='voyageur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
