# Generated by Django 5.1.3 on 2026-05-10 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyageurs', '0016_expediteur_email_voyageur_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-date_envoi']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='date',
            new_name='date_envoi',
        ),
        migrations.RemoveField(
            model_name='message',
            name='expediteur',
        ),
        migrations.RemoveField(
            model_name='message',
            name='voyageur',
        ),
        migrations.AddField(
            model_name='message',
            name='matching',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='voyageurs.matching'),
        ),
        migrations.AlterField(
            model_name='message',
            name='contenu',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='messages/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(choices=[('expediteur', 'Expéditeur'), ('voyageur', 'Voyageur')], max_length=20),
        ),
    ]
