# Generated by Django 5.1.3 on 2026-05-10 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyageurs', '0017_alter_message_options_rename_date_message_date_envoi_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['date']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='date_envoi',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='message',
            name='matching',
        ),
        migrations.AddField(
            model_name='message',
            name='expediteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voyageurs.expediteur'),
        ),
        migrations.AddField(
            model_name='message',
            name='voyageur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voyageurs.voyageur'),
        ),
        migrations.AlterField(
            model_name='message',
            name='contenu',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='messages_photos/'),
        ),
    ]
