# Generated by Django 5.1.3 on 2026-05-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyageurs', '0018_alter_message_options_rename_date_envoi_message_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_id', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('date_premiere_visite', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_visite', models.DateTimeField(auto_now=True)),
                ('nb_visites', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='expediteur',
            name='guest_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='messagesupport',
            name='guest_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profil',
            name='guest_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='retrait',
            name='guest_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='retrait',
            name='mode_retrait',
            field=models.CharField(choices=[('orange', 'Orange Money'), ('paypal', 'PayPal'), ('carte', 'Carte bancaire'), ('wave', 'Wave'), ('wise', 'Wise'), ('revolut', 'Revolut'), ('virement', 'Virement bancaire')], max_length=20),
        ),
        migrations.AlterField(
            model_name='voyageur',
            name='guest_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
