# Generated by Django 5.1.3 on 2026-07-31 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyageurs', '0019_visiteur_alter_expediteur_guest_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediteur',
            name='prix_par_kg',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='voyageur',
            name='prix_par_kg',
            field=models.FloatField(default=10.0),
        ),
        migrations.AlterField(
            model_name='expediteur',
            name='commission',
            field=models.FloatField(default=2.99),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='montant_commission',
            field=models.FloatField(default=2.99),
        ),
    ]
