# Generated by Django 5.1.3 on 2026-08-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyageurs', '0020_expediteur_prix_par_kg_voyageur_prix_par_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='guest_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
