# Generated by Django 5.1.3 on 2026-08-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyageurs', '0021_alter_profil_guest_id_alter_profil_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='date_envoi_verification',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='email_verifie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profil',
            name='token_verification_email',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
