from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('ajouter-voyageur/', views.ajouter_voyageur, name='ajouter_voyageur'),
    path('ajouter-expediteur/', views.ajouter_expediteur, name='ajouter_expediteur'),
    path('creer-profil/', views.creer_profil, name='creer_profil'),
    path('login-profil/', views.login_profil, name='login_profil'),
    path('login/', views.page_login, name='page_login'),
    path('historique/', views.historique, name='historique'),
    path('espace-connecte/', views.espace_connecte, name='espace_connecte'),
    path('repondre-matching/', views.repondre_matching, name='repondre_matching'),
    path('paiement/', views.page_paiement, name='page_paiement'),
    path('traiter-paiement/', views.traiter_paiement, name='traiter_paiement'),
    path('debloquer-paiement/', views.debloquer_paiement, name='debloquer_paiement'),
    path('envoyer-message/', views.envoyer_message, name='envoyer_message'),
    path('get-messages/', views.get_messages, name='get_messages'),
    path('envoyer-message-support/', views.envoyer_message_support, name='envoyer_message_support'),
    path('get-messages-support/', views.get_messages_support, name='get_messages_support'),
    path('demander-remboursement/', views.demander_remboursement, name='demander_remboursement'),
    path('creer-profil-page/', views.creer_profil_page, name='creer_profil_page'),
    path('verifier-paiement/', views.verifier_paiement, name='verifier_paiement'),
    path('google-callback/', views.google_callback, name='google_callback'),
    path('completer-profil-google/', views.completer_profil_google, name='completer_profil_google'),
    path('confirmer-livraison/', views.confirmer_livraison_voyageur, name='confirmer_livraison'),
    path('confirmer-reception/', views.confirmer_reception_expediteur, name='confirmer_reception'),
    path('get-portefeuille/', views.get_portefeuille, name='get_portefeuille'),
    path('demander-retrait/', views.demander_retrait, name='demander_retrait'),
    path('get-expediteur-info/', views.get_expediteur_info, name='get_expediteur_info'),
    path('get-voyageur-info/', views.get_voyageur_info, name='get_voyageur_info'),
    path('creer-matching-apres-login/', views.creer_matching_apres_login, name='creer_matching_apres_login'),
    path('accepter-demande/', views.accepter_demande, name='accepter_demande'),
    path('refuser-demande/', views.refuser_demande, name='refuser_demande'),
    path('changer-langue/', views.changer_langue, name='changer_langue'),
    path('get-solde/', views.get_solde_temps_reel, name='get_solde'),
    path('generer-facture-remboursement/<int:transaction_id>/', views.generer_facture_remboursement, name='generer_facture_remboursement'),
    path('nb-visiteurs/', views.nb_visiteurs, name='nb_visiteurs'),
]